### ISSUE TITLE
PDF export?

### ISSUE THREAD

**Issue by kumaresan-subramani** [mumincelal/ngx-org-chart#70] opened 2022-08-25 06:55 UTC
pdf export support is available?

i have tried to export like below but it is not working as expected

sample - https://stackblitz.com/edit/ng-orgchart-v8f2pt?file=src%2Findex.html,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by mumincelal** [comment] 2023-12-11 20:33
Duplicate of #22

**Closed as completed by mumincelal** 2023-12-11 20:33 UTC
Labels: duplicate
